name: Test Poetry Dependencies

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install GitHub CLI
      run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0 && sudo apt-add-repository https://cli.github.com/packages && sudo apt update && sudo apt install gh

    - name: Authenticate using GitHub CLI
      run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${{ runner.tool_cache }}/python/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry config repositories.private-repo https://github.com/testing-organization-jcayllahua/package-artifacts/releases/download/
        poetry install
